### ISSUE TITLE
User Story - Landing Page

### ISSUE THREAD

**Issue by BrianMcConway** [Dee-McG/Hackathon-July-2024#1]
As a **user** I can **view the landing page** so that **I understand the purpose of the game and how to start playing.**

** Acceptance Criteria **

* The landing page includes the game(s) title(s) and a brief description.
* The page is mobile-responsive.
* The landing page includes links to resources about Pride and LGBTQ+ history.

**Design**

![Image](https://github.com/user-attachments/assets/7daae90f-050d-40ae-a418-5fc3f60ad568)

**Comment by Naviid24** [comment]
done
