### ISSUE TITLE
User Story - Question & Answer Flag Display

### ISSUE THREAD

**Issue by BrianMcConway** [Dee-McG/Hackathon-July-2024#2]
As a **user** I can **see a question and 4 pride flags on the game screen** so that **I can choose which ones to match.**

**Acceptance Criteria**

* Question is displayed
* A set of pride flags is displayed in a 2x2 grid
* Each flag is clearly visible and distinguishable.
* Flags are displayed in a random order each game session.

**Tasks**

- [ ] When user clicks the Flag Quiz on the home page, it will load the quiz

**Design**

![Image](https://github.com/user-attachments/assets/34a8263a-3fa4-4e93-b23a-065aeddeb93a)

**Comment by caleom** [comment]
flag game code pen

https://codepen.io/mohana-shiva/pen/zEpxKW
